### PR TITLE
Update sync-uploads to output overall progress

### PR DESCRIPTION
**Pull request by rossey**
Added `--info=progress2` and removed the `-v` (verbose) output for rsync

### CODE REVIEW

**Comment by dave1010** [comment]
Does `--info=progress2` work on versions of rsync shipped with Centos 6 / Ubuntu 12.04?

**Comment by rossey** [comment]
Good point I did consider this, not sure if you only need version `>= 3.1.0` on the client side for progress2

**Comment by rossey** [comment]
bump @dave1010 do you know?

**Comment by dave1010** [comment]
@rossey no idea :-)

**Comment by chrisnx** [comment]
As we are unsure, I won't merge this in to the core shell script.

I have however added an option into bosh-config to give users the ability to add more parameters to this command, so if users have the ability to add --info=progress2 they can - and we can on a per-project basis.

https://github.com/wearebase/base-bash-bosh/commit/8eacd413fc091f0c0a4be2f65a7d279caef8c5cf

**Comment by rossey** [comment]
:+1: much better way of implementing this

**Pull request closed without merging**
